name: Waka Readme

on:
  schedule:
    - cron: '*/300 * * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS:
          SHOW_TIMEZONE:
          SHOW_EDITORS: 
          SHOW_COMMIT: 
          SHOW_LANGUAGE: 
          SHOW_LINES_OF_CODE: "True" # optional, default is False
          SHOW_LANGUAGE_PER_REPO: 
          SHOW_LOC_CHART: 
          SHOW_DAYS_OF_WEEK: 
          SHOW_PROFILE_VIEWS: 
          SHOW_SHORT_INFO: 
          LOCALE: "en"
