# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Current configuration doesn't require a GitHub token
          token: NOT_NEEDED
          filename: images/steam.svg

          # Options
          user: Vault108
          template: classic
          base: ""
          base_skip: yes
          config_timezone: America/New_York
          plugin_steam: yes
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 1
          plugin_steam_playtime_threshold: 2
          plugin_steam_recent_games_limit: 1
          plugin_steam_sections: player, most-played, recently-played
          plugin_steam_user: Kleeperson
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
